version: '3.1'

services:

  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./php/file:/var/www/html/
    ports:
      - 8080:80
    links: 
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    restart: always
    volumes: 
      - ./db/dumb/:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Wiosna2424
      MYSQL_DATABASE: cdvdb
      MYSQL_USER: cvd
      MYSQL_PASSWORD: Wiosna2424
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    links:
      - db