version: '3'

services: 
  db:
    image: mysql
    restart: always
    environment: 
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: "test1234"
    ports: 
      - '3306:3306'
    expose: 
      - '3306'
    volumes: 
      - mysql_data:/var/lib/mysql
volumes: 
  mysql_data: