name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: Azure/login@v2.1.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set Git Commit SHA
      run: |
        echo "GIT_COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Docker build and push ACR
      run: |
        echo ${{ secrets.REGISTRY_LOGIN_SERVER }}/geofencing-ui:${{github.run_number}}
        echo ${{github.workspace}}/deployment/Dockerfile
        az acr login --name ${{ secrets.REGISTRY_LOGIN_SERVER }}
        docker build -t zvoovetesting.azurecr.io/geofencing-ui:${{github.run_number}} -f ${{github.workspace}}/deployment/Dockerfile
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/geofencing-ui:${{github.run_number}}

  
    
