name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: zvoovetesting.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file deployment/Dockerfile --tag my-image-name:$(date +%s)
